# Generated by Django 5.1.3 on 2024-11-14 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_task_delete_choice_delete_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='desciption',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='dueDate',
            new_name='due_date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='tittle',
            new_name='title',
        ),
    ]
