# Generated by Django 5.1.3 on 2024-11-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_desciption_task_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_Completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'completed')], max_length=20),
        ),
    ]
