# Generated by Django 5.1.3 on 2024-11-17 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_task_is_completed_alter_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='is_Completed',
            new_name='is_completed',
        ),
    ]
